version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: todo-service
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

volumes:
  mongo_data: